export const languages = [
   {
      spanish: 'Español',
      english: 'Inglés',
      login: 'Iniciar sesión',
      register: 'Registrarse',
      Did_you_forget_your_password: '¿Olvidaste tu contraseña?',
      home: 'Inicio',
      dashboard: 'Panel',
      logout: 'Cerrar sesión',
      Play_chess_online_and_improve_your_skills: 'Juega ajedrez online y mejora tus habilidades!',
      fast: 'Rapida',
      bullet: 'Bala',
      join_a_room: 'Unirse a una sala',
      loading_user_statistics: 'Cargando estadisticas del usuario',
      statistics_of: 'Estadisticas de',
      rating: 'Clasificación',
      total_games: 'Partidas totales',
      win: 'Victorias',
      lost: 'Derrotas',
      draw: 'Empates',
      win_streak: 'Racha ganadora',
      rank: 'Rango',
      game_history: 'Historial de partidas',
      Last_games_of: 'Ultimas partidas de',
      Language: 'Idioma',
      profile: 'Editar perfil'
   },
   {
    spanish: 'Spanish',
    english: 'English',
    login: 'Login',
    register: 'Register',
    did_you_forget_your_password: 'Did you forget your password?',
    home: 'Home',
    dashboard: 'Dashboard',
    logout: 'Logout',
    play_chess_online_and_improve_your_skills: 'Play chess online and improve your skills!',
    fast: 'Fast',
    bullet: 'Bullet',
    join_a_room: 'Join a room',
    loading_user_statistics: 'Loading user statistics:',
    statistics_of: 'Statistics of',
    rating: 'Rating',
    total_games: 'Total games',
    win: 'Win',
    lost: 'Lost',
    draw: 'Draw',
    win_streak: 'Win streak',
    rank: 'Rank',
    game_history: 'Games history',
    Last_games_of: 'Last games of',
    Language: 'Languaje',
    profile: 'Edit profile'
   }
];