export const languages = [
   {
      spanish: 'Español',
      english: 'Inglés',
      login: 'Iniciar sesión',
      register: 'Registrarse',
      Did_you_forget_your_password: '¿Olvidaste tu contraseña?',
      home: 'Inicio',
      dashboard: 'Panel',
      logout: 'Cerrar sesión',
      Play_chess_online_and_improve_your_skills: 'Juega ajedrez online y mejora tus habilidades!',
      fast: 'Rapida',
      bullet: 'Bala',
      join_a_room: 'Unirse a una sala',
      loading_user_statistics: 'Cargando estadisticas del usuario',
      statistics_of: 'Estadisticas de',
      rating: 'Clasificación',
      total_games: 'Partidas totales',
      win: 'Victorias',
      lost: 'Derrotas',
      draw: 'Empates',
      win_streak: 'Racha ganadora',
      rank: 'Rango',
      game_history: 'Historial de partidas',
      Last_games_of: 'Ultimas partidas de',
      Language: 'Idioma',
      profile: 'Editar perfil',
      Challenge_a_match: 'Desafia una partida a',
      Loading_Players: 'Cargando jugadores',
      information: 'Información',
      You_have_sent_a_challenge: 'Has enviado un desafio',
      Challenge_rejected: 'Desafio rechazado',
      Challenge: 'Desafiar',
      message: 'Mensaje',
      Cancel: 'Cancelar',
      game_of: 'Partida de',
      has_challenged_you: 'te ha desafiado',
      Accept: 'Aceptar',
   },
   {
    spanish: 'Spanish',
    english: 'English',
    login: 'Login',
    register: 'Register',
    did_you_forget_your_password: 'Did you forget your password?',
    home: 'Home',
    dashboard: 'Dashboard',
    logout: 'Logout',
    play_chess_online_and_improve_your_skills: 'Play chess online and improve your skills!',
    fast: 'Fast',
    bullet: 'Bullet',
    join_a_room: 'Join a room',
    loading_user_statistics: 'Loading user statistics:',
    statistics_of: 'Statistics of',
    rating: 'Rating',
    total_games: 'Total games',
    win: 'Win',
    lost: 'Lost',
    draw: 'Draw',
    win_streak: 'Win streak',
    rank: 'Rank',
    game_history: 'Games history',
    Last_games_of: 'Last games of',
    Language: 'Languaje',
    profile: 'Edit profile',
    Challenge_a_match: 'Challenge a match',
    Loading_Players: 'Loading Players',
    information: 'Information',
    You_have_sent_a_challenge: 'You have sent a challenge',
    Challenge_rejected: 'Challenge rejected',
    Challenge: 'Challenge',
    message: 'Message',
    Cancel: 'Cancel',
    game_of: 'Game of',
    has_challenged_you: 'has challenged you',
    Accept: 'Accept'
   }
];